### ISSUE TITLE
EfficientDetRetinaNet error

### ISSUE THREAD

**Issue by cloudfool** [zzzxxxttt/simple_detectron2_EfficientDet#4]
Hi,
I got this  following error when I run the code:

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 20, in _wrap
    fn(i, *args)
  File "/root/jwei/detectron2/detectron2/engine/launch.py", line 94, in _distributed_worker
    main_func(*args)
  File "/root/jwei/detectron2/projects/Onlyou/train_net.py", line 94, in main
    trainer = Trainer(cfg)
  File "/root/jwei/detectron2/detectron2/engine/defaults.py", line 282, in __init__
    model = self.build_model(cfg)
  File "/root/jwei/detectron2/detectron2/engine/defaults.py", line 440, in build_model
    model = build_model(cfg)
  File "/root/jwei/detectron2/detectron2/modeling/meta_arch/build.py", line 21, in build_model
    model = META_ARCH_REGISTRY.get(meta_arch)(cfg)
  File "/root/jwei/detectron2/projects/Onlyou/model/efficientnet/retinanet.py", line 27, in __init__
    self.device = torch.device(cfg.MODEL.DEVICE)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 638, in __setattr__
    object.__setattr__(self, name, value)
AttributeError: can't set attribute

Could you pls give me advice ? thanks

**Comment by cloudfool** [comment]
I also found another problem in retinanet.py
gt_classes, gt_anchors_reg_deltas = self.get_ground_truth(anchors, gt_instances),
which "get_ground_truth" is not implemented
